//Опросник пользователя
POST http://localhost:3338/api/questionnaire HTTP/1.1
Content-Type: application/json

{
  "trainLevel": "newbie",
  "typesTraining": "yoga",
  "timeTraining": 30,
  "resetCalories": 400,
  "spendCaloriesPerDay": 2000,
  "readTrainig": true
}
###


POST http://localhost:3338/api/questionnaire-coach HTTP/1.1
Content-Type: application/json

{
  "trainLevel": "newbie",
  "typesTraining": "yoga",
  "sertificates": "http://localhost:3338/api/setificates/1.jpg",
  "merits": "Long work coach for 40 years",
  "personalTraining": true
}
###