//Сервис Персональная тренировка

POST http://localhost:3337/api/personal-training HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI2MTVjMDdiMjc5NmVkMjM3OWQzNzAiLCJlbWFpbCI6IjFAbWFpbC5ydSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTY4MDI4ODg4MCwiZXhwIjoxNjgwMjg5NzgwfQ.qYiTOdj3CVQTKxK1LEHKE6IRsbxT54V266ZP1XJScOo

{
  "initiator": "642615c07b2796ed2379d370",
  "user": "6426d650929b8c338ce73f7e",
  "changeStatus": "2023-03-21T19:59:15.563Z",
  "status": "pending"
}

###

PUT http://localhost:3337/api/personal-training/641ecada6cc93df19ded32b2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDFhMGM1ODM0M2I1M2YwMjcwNDY3MDYiLCJlbWFpbCI6IjFAbWFpbC5ydSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTY3OTc4MDAzMywiZXhwIjoxNjc5NzgwOTMzfQ.RE8NuWMc1VDRXpzBFJ1LgCuYTSucNttAbZIdVlyHXFI

{
  "initiator": "641ecada6cc93df19ded32b2",
  "user": "641a0c58343b53f027046706",
  "changeStatus": "2023-03-21T19:59:15.563Z",
  "status": "pending"
}

###