//Сервис Персональная тренировка
@Host = localhost
@Port = 3337
@ApiKey = Bearer api-key-one
@TrainingId = id

### Создание оповещения о персольнальной тренировке
POST http://{{Host}}:{{Port}}/api/personal-training/create HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
  "initiator": "642858ae021f7d1433c22c74",
  "user": "642858ae021f7d1433c22c72",
  "status": "pending"
}
###

### Получение списка друзей
GET http://{{Host}}:{{Port}}/api/personal-training/all HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###


### Редактирование оповещения о персольнальной тренировке
PUT http://{{Host}}:{{Port}}/api/personal-training/{{TrainingId}} HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
  "status": "accepted"
}

###