//Сервис Персональная тренировка

### Создание оповещения о персольнальной тренировке
POST http://localhost:3337/api/personal-training/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {token}

{
  "initiator": "642858ae021f7d1433c22c74",
  "user": "642858ae021f7d1433c22c72",
  "status": "pending"
}
###

### Получение списка друзей
GET http://localhost:3337/api/personal-training/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer {token}
###


### Редактирование оповещения о персольнальной тренировке
PUT http://localhost:3337/api/personal-training/{trainingId} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {token}

{
  "status": "accepted"
}

###