//Сервис Спорт зал
@Host = localhost
@Port = 3334
@ApiKey = Bearer api-key-one
@GymId = id

### Создание зала
POST http://{{Host}}:{{Port}}/api/gym/create HTTP/1.1
Content-Type: application/json
{
  "title": "string",
  "location": "Пионерская",
  "verify": true,
  "parameters": [
    "swimmingPool", "freeParking"
  ],
  "photos": [
    "http://localhost:3339/workout/image/training-1.jpg"
  ],
  "description": "stringstringstringstringstring",
  "price": 1000
}

###

### Получение всех залов
GET http://{{Host}}:{{Port}}/api/gym/all HTTP/1.1

###

### Получение зала по ID
GET http://{{Host}}:{{Port}}/api/gym/{{GymId}} HTTP/1.1

###


### Загрузка изображения
POST http://{{Host}}:{{Port}}/api/gym/upload HTTP/1.1
Content-Type: multipart/form-data
###


### Получение изображения
GET  http://{{Host}}:{{Port}}/api/gym/upload/{filename} HTTP/1.1
Content-Type: multipart/form-data
###