//Сервис Пользователи
@Host = localhost
@Port = 3338

# @name login 
POST http://{{Host}}:{{Port}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "newMan@mail.ru",
  "password": "1234567"
}
###
@ApiKey = Bearer {{login.response.body.accessToken}}
@UserId = {{login.response.body.id}}


### Регистрация пользователя
POST http://{{Host}}:{{Port}}/api/fit-user/register HTTP/1.1
Content-Type: application/json

{
  "username": "FooBar",
  "email": "newMan@mail.ru",
  "avatar": "http://localhost:3338/api/fit-user/avatar/user-2023-03-27T00-43-48.jpg",
  "password": "1234567",
  "gender": "male",
  "dateBirth": "1981-03-12",
  "role": "coach",
  "location": "Пионерская"
}
###


### Опросник тренера
POST http://{{Host}}:{{Port}}/api/questionnaire-coach/ HTTP/1.1
Content-Type: application/json
Authorization:{{ApiKey}}

{
  "trainLevel": "newbie",
  "typesTraining": ["yoga"],
  "sertificates": "http://localhost:3338/api/setificates/1.pdf",
  "merits": "Long work coach for 40 years",
  "personalTraining": true
}
###

### Опросник пользователя
POST http://{{Host}}:{{Port}}/api/questionnaire/ HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
  "trainLevel": "newbie",
  "typesTraining": ["yoga"],
  "timeTraining": 30,
  "resetCalories": 2000,
  "spendCaloriesPerDay": 2000,
  "readTrainig": true
}
###


### Вход в систему
POST http://{{Host}}:{{Port}}/api/auth/login HTTP/1.1
Content-Type: application/json 

{
  "email": "newMan@mail.ru",
  "password": "1234567"
}
###


### Редактирование информации о пользователе
PUT http://{{Host}}:{{Port}}/api/fit-user/update HTTP/1.1
Content-Type: application/json 
Authorization: {{ApiKey}}

{
  "username": "John",
  "gender": "male"
}
###

### Список пользователей
GET http://{{Host}}:{{Port}}/api/fit-user/list HTTP/1.1
Authorization: {{ApiKey}}
###


### Детальная информация о пользователе
GET http://{{Host}}:{{Port}}/api/fit-user/{{UserId}}
Authorization: {{ApiKey}}
###


### Refresh token
POST http://{{Host}}:{{Port}}/api/auth/refresh HTTP/1.1
Content-Type: application/json 

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI2MTVjMDdiMjc5NmVkMjM3OWQzNzAiLCJlbWFpbCI6IjFAbWFpbC5ydSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTY4MDI2NTIxNSwiZXhwIjoxNjgwMjY2MTE1fQ.SWSH_F9F4PpfNC3G7ygNh968S9mjkY_Rc_FcOouEBE0"
}
###



