//Сервис Пользователи

### Регистрация пользователя
POST http://localhost:3338/api/fit-user/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIwYzE0MzI4MTJkNjhlYjBjNDBlNjUiLCJlbWFpbCI6IjFAbWFpbC5ydSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjc5ODY5NDk0LCJleHAiOjE2Nzk4NzAzOTR9.Y05YWg6GcyEbFk5F6beijL6Q_uIxPeDX2kHLSlYRwLc

{
  "username": "FooBar",
  "email": "2@mail.ru",
  "avatar": "http://localhost:3338/api/fit-user/avatar/user-2023-03-27T00-43-48.jpg",
  "password": "1234567",
  "gender": "male",
  "dateBirth": "1981-03-12",
  "role": "coach",
  "location": "Пионерская"
}
###


### Опросник пользователя
POST http://localhost:3338/api/questionnaire/6420ca54ac103330b69a1709 HTTP/1.1
Content-Type: application/json

{
  "userId": "64260d16bd98d069c594b563",
  "trainLevel": "newbie",
  "typesTraining": ["yoga"],
  "timeTraining": 30,
  "resetCalories": 2000,
  "spendCaloriesPerDay": 2000,
  "readTrainig": true
}
###


### Опросник тренера
POST http://localhost:3338/api/questionnaire-coach/642615c07b2796ed2379d370 HTTP/1.1
Content-Type: application/json

{
  "userId": "642615c07b2796ed2379d370",
  "trainLevel": "newbie",
  "typesTraining": ["yoga"],
  "sertificates": "http://localhost:3338/api/setificates/1.pdf",
  "merits": "Long work coach for 40 years",
  "personalTraining": true
}
###


### Вход в систему
POST http://localhost:3338/api/auth/login HTTP/1.1
Content-Type: application/json 

{
  "email": "2@mail.ru",
  "password": "1234567"
}
###


### Редактирование информации о пользователе
PUT http://localhost:3338/api/fit-user/update/642615c07b2796ed2379d370 HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI2MTVjMDdiMjc5NmVkMjM3OWQzNzAiLCJlbWFpbCI6IjFAbWFpbC5ydSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTY4MDIxNzk1NCwiZXhwIjoxNjgwMjE4ODU0fQ.degG26VglBxCZyXIJTXITLEyorYvjN8dB-yC6npy-cY

{
  "username": "John",
  "gender": "male"
}
###


### Список пользователей
GET http://localhost:3338/api/fit-user/list HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI2MTVjMDdiMjc5NmVkMjM3OWQzNzAiLCJlbWFpbCI6IjFAbWFpbC5ydSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTY4MDIxNzk1NCwiZXhwIjoxNjgwMjE4ODU0fQ.degG26VglBxCZyXIJTXITLEyorYvjN8dB-yC6npy-cY
###


### Детальная информация о пользователе
GET http://localhost:3338/api/fit-user/642615c07b2796ed2379d370
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI2MTVjMDdiMjc5NmVkMjM3OWQzNzAiLCJlbWFpbCI6IjFAbWFpbC5ydSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTY4MDIxNzk1NCwiZXhwIjoxNjgwMjE4ODU0fQ.degG26VglBxCZyXIJTXITLEyorYvjN8dB-yC6npy-cY
###


### Refresh token
POST http://localhost:3338/api/auth/refresh HTTP/1.1
Content-Type: application/json 

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI2MTVjMDdiMjc5NmVkMjM3OWQzNzAiLCJlbWFpbCI6IjFAbWFpbC5ydSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTY4MDI2NTIxNSwiZXhwIjoxNjgwMjY2MTE1fQ.SWSH_F9F4PpfNC3G7ygNh968S9mjkY_Rc_FcOouEBE0"
}
###



