
export enum Approute {
  Into = '/',
  Home = '/home',
  SignUp = '/sign-up',
  SignIn = '/sign-in',
  UserQuestion = '/user-question',
  CoachQuestion = '/coach-question',
  FriendsListUser = '/friends-list-user',
  FriendsListCoach = '/friends-list-coach',
  CreateTraining = '/create-training',
  FoodDiary = '/food-diary',
  GymsCatalog = '/gyms-catalog',
  GymCard = '/gyms-catalog/:id',
  MyGyms = '/my-gyms',
  MyOrders = '/my-orders',
  MyPurchases = '/my-purchases',
  MyTraining = '/my-training',
  PersonalAccountCoach = '/personal-account-coach',
  PersonalAccountUser = '/personal-account-user',
  PopupBuy = '/popup-buy',
  PopupFeedback = '/popup-feedback',
  PopupGymMap = 'popup-gym-map',
}