//Сервис комментарии 
@Host = localhost
@Port = 3333
@ApiKey = Bearer api-key-one
@WorkoutId = id

### Создание комментария

POST http://{{Host}}:{{Port}}/api/comment/{{WorkoutId}} HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
{
  "rating": 1,
  "review": "string"
}
###


### Получение всех комментариев к тренировке

GET http://{{Host}}:{{Port}}/api/comment/{{WorkoutId}} HTTP/1.1

###