//Сервис комментарии 

@Host = localhost
@Port = 3333

@CoachId = {{login.response.body.id}}

# @name login 
POST http://{{Host}}:3338/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "newMan@mail.ru",
  "password": "1234567"
}

@ApiKey = Bearer {{login.response.body.accessToken}}
###

# @name workout
POST http://{{Host}}:3339/api/workout/new HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
  "title": "The best hard",
  "trainLevel": "newbie",
  "typeTraining": "yoga",
  "timeTraining": 30,
  "price": 1000,
  "calories": 1000,
  "description": "No pain no gain",
  "gender": "male",
  "movie": "http://localhost:3339/api/workout/movies/workout-2023-03-27T00-34-33.avi",
  "rating": 5,
  "coach": "6437d1cd4ba88e37a5aad724",
  "specialOffer": false
}
###
@WorkoutId = {{workout.response.body.id}}


### Создание комментария

POST http://{{Host}}:{{Port}}/api/comment/{{WorkoutId}} HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
  "rating": 1,
  "review": "stringstringstringstringstringstringstringstringstringstringstringstringstringstrinstringstringstringstringstringg"
}
###


### Получение всех комментариев к тренировке
GET http://{{Host}}:{{Port}}/api/comment/{{WorkoutId}} HTTP/1.1

###