version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: fitfriends.order.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: fitfriends-order
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27019/fitfriends-order --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 27020:27017
    volumes:
      - ./db:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: fitfriends.order.mongo-express
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/
      