//Сервис заказ
@Host = localhost
@Port = 3336
@ApiKey = Bearer {{login.response.body.accessToken}}
@OrderId = {{order.response.body.id}}

# @name login 
POST http://{{Host}}:3338/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "newMan@mail.ru",
  "password": "1234567"
}
###

### Создание заказа
# @name order
POST http://{{Host}}:{{Port}}/api/order/create HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
  "purchase": "training",
  "service": "642858ae021f7d1433c22c76",
  "price": 1000,
  "quantity": 2,
  "paymentMethod": "visa"
}
###

### Получение всех заказов
GET http://{{Host}}:{{Port}}/api/order/all HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###

### Получение заказа по ID
GET http://{{Host}}:{{Port}}/api/order/{{OrderId}} HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###