///Тренировка
@Host = localhost
@Port = 3339
@ApiKey = Bearer api-key-one
@WorkoutId = id
@CoachId = id

### Создание тренировки
POST http://{{Host}}:{{Port}}/api/workout/new HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
  "title": "The best hard workout",
  "trainLevel": "newbie",
  "typeTraining": "yoga",
  "timeTraining": 30,
  "price": 1000,
  "calories": 1000,
  "description": "No pain no gain",
  "gender": "male",
  "movie": "http://localhost:3339/api/workout/movies/workout-2023-03-27T00-34-33.avi",
  "rating": 5,
  "coach": "343fds43424ds2434",
  "specialOffer": false
}
###

### Получение тренировок пользователя
GET http://{{Host}}:{{Port}}/api/workout/all/{{@CoachId}} HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###

### Получение информации о тренировке по ID
GET http://{{Host}}:{{Port}}/api/workout/{{WorkoutId}} HTTP/1.1
Content-Type: application/json
###

### Редактирование тренировки
PUT http://{{Host}}:{{Port}}/api/workout/{{WorkoutId}} HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
  "title": "The best hard workout",
  "trainLevel": "newbie",
  "typeTraining": "yoga",
  "timeTraining": 30,
  "price": 1000,
  "calories": 1000,
  "description": "pain no gain",
  "gender": "male",
  "movie": "http://localhost:3339/api/workout/movies/workout-2023-03-27T00-34-33.avi",
  "rating": 5,
  "specialOffer": true
}
###