///Тренировка

### Создание тренировки
POST http://localhost:3339/api/workout/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIwZDlhNWFlMzg4NjdhNzg0OTY3OTMiLCJlbWFpbCI6IjJAbWFpbC5ydSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTY3OTkxMjgwMywiZXhwIjoxNjc5OTEzNzAzfQ.nBellcwSiHcgV5UI_dfUYgI27SSYQb1JmyM6wi361RQ

{
  "title": "The best hard workout",
  "image": "http://localhost:3339/api/workout/pictures/workout-2023-03-27T00-34-33.jpg",
  "trainLevel": "newbie",
  "typeTraining": "yoga",
  "timeTraining": 30,
  "price": 100,
  "calories": 100,
  "description": "No pain no gain",
  "gender": "male",
  "movie": "http://localhost:3339/api/workout/movies/workout-2023-03-27T00-34-33.avi",
  "rating": 5,
  "coach": "343fds43424ds2434",
  "specialOffer": false
}
###

### Редактирование тренировки
PUT http://localhost:3339/api/workout/64216f9cc4ce22b709aeba1c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDIwZDlhNWFlMzg4NjdhNzg0OTY3OTMiLCJlbWFpbCI6IjJAbWFpbC5ydSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTY3OTkxNDI0MywiZXhwIjoxNjc5OTE1MTQzfQ.9egw8_JiWch_-bPAgNaBM7N47PxwOq4bBsTulHVjtpg

{
  "title": "The best hard workout",
  "gender": "female"
}
###