///Тренировка

### Создание тренировки
POST http://localhost:3339/api/workout/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer {TOKEN}

{
  "title": "The best hard workout",
  "trainLevel": "newbie",
  "typeTraining": "yoga",
  "timeTraining": 30,
  "price": 1000,
  "calories": 1000,
  "description": "No pain no gain",
  "gender": "male",
  "movie": "http://localhost:3339/api/workout/movies/workout-2023-03-27T00-34-33.avi",
  "rating": 5,
  "coach": "343fds43424ds2434",
  "specialOffer": false
}
###

### Получение тренировок пользователя
GET http://localhost:3339/api/workout/all/{coachId} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {TOKEN}
###

### Получение информации о тренировке по ID
GET http://localhost:3339/api/workout/{workoutId} HTTP/1.1
Content-Type: application/json
###

### Редактирование тренировки
PUT http://localhost:3339/api/workout/{id} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {token}

{
  "title": "The best hard workout",
  "trainLevel": "newbie",
  "typeTraining": "yoga",
  "timeTraining": 30,
  "price": 1000,
  "calories": 1000,
  "description": "pain no gain",
  "gender": "male",
  "movie": "http://localhost:3339/api/workout/movies/workout-2023-03-27T00-34-33.avi",
  "rating": 5,
  "specialOffer": true
}
###